export const listLocationEntriesPaginated = /* GraphQL */ `
  query listLocationEntriesPaginated($page: Int, $limit: Int, $filters: Any) {
    listLocationEntriesPaginated(page: $page, limit: $limit, filters: $filters) {
      docs {
        _id
        contact {
          _id
          firstName
          lastName
          email
          phone
          DPI
          nickname
          verified
          typeVerified
          banFinish
          createdAt
          updatedAt
          empresa
        }
        location {
          _id
          address
          name
          typeCheck
          createdAt
          updatedAt
          state
          abbreviation
          deletedDate
          admins {
            _id
            name
            lastname
            email
          }
        }
        event {
          _id
          name
          start
          end
          host {
            _id
            name
            lastname
            email
            codeWorker
            active
            country
            token
            verifyLogin
            createdAt
            tokenExpo
            updatedAt
            canCreateHost
            allEventWithAuth
            canAccessToApp
            canAccessToWeb
            document
            typeDocument
            code
            phone
            QR
            canUseAuthenticator
            banFinish
          }
          beforeStart
          onlyAuthUser
          createdAt
          updatedAt
          state
          deletedDate
        }
        hourIn
        hourOut
        host {
          _id
          name
          lastname
          email
          active
          country
          token
          verifyLogin
          createdAt
          updatedAt
          canCreateHost
          allEventWithAuth
          canAccessToApp
          canAccessToWeb
          document
          typeDocument
          code
          phone
          QR
          canUseAuthenticator
          banFinish
        }
        type
        worker {
          _id
          name
          lastname
          email
          verifyLogin
          active
          phone
          document
          typeDocument
          QR
          canAccessToApp
          canAccessToWeb
          canUseAuthenticator
          banFinish
          code
          createdAt
          updatedAt
        }
        user {
          _id
          name
          lastname
          email
          active
          country
          token
          verifyLogin
          createdAt
          updatedAt
          canCreateHost
          allEventWithAuth
          canAccessToApp
          canAccessToWeb
          document
          typeDocument
          code
          phone
          QR
          canUseAuthenticator
          banFinish
        }
        visitantData {
          direction
        }
        eventExpress {
          _id
          name
          start
          end
          state
          host {
            _id
            name
            lastname
            email
            codeWorker
            active
            country
            token
            verifyLogin
            createdAt
            tokenExpo
            updatedAt
            canCreateHost
            allEventWithAuth
            canAccessToApp
            canAccessToWeb
            document
            typeDocument
            code
            phone
            QR
            canUseAuthenticator
            banFinish
          }
          createdAt
          updatedAt
          motivo
        }
        typeQr
        createdAt
        updatedAt
      }
      totalDocs
      limit
      page
      totalPages
      pagingCounter
      hasPrevPage
      hasNextPage
      offset
      prevPage
      nextPage
    }
  }
`
